name: Auto Commit

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */3 * * *"   # 01:00 WIB setiap hari
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Git
        run: |
          git config --global user.name "MHFADev"
          git config --global user.email "hilmi.firjatullah12@gmail.com"

      - name: Make changes
        run: |
          echo "$(date)" >> log.txt

      - name: Commit & Push
        run: |
          git add .
          git commit -m "chore: daily auto commit" || echo "No changes to commit"
          git push origin HEAD:main
